### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Julia-Shu/grid-template#1]
1)
Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/138641648-15821dd3-e0a3-44e3-9272-58cf0a6065e4.png)

2)
Невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/138641688-2f5baef5-0722-448d-b95c-5fb898ce8773.png)

3)
Не соответствует поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/138641836-57800267-58b5-4d61-9651-697e90fdb1df.png)
![image](https://user-images.githubusercontent.com/8464662/138641858-ba471b17-3ce7-4120-877c-f5f89a68cacf.png)

4)
Не соответствует поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/138641885-69242dd4-6b35-4af0-a3a5-376bbd2aff63.png)

5)
Не соответствует поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/138641915-4940ff57-f3cc-4b07-a410-db7f6e2bc7db.png)

6)
Не соответствует поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/138641966-40764ab6-2d4c-44fc-a0fa-390b68263c78.png)

**Comment by Julia-Shu** [comment]
Пане Андрію, 
повиправляла багато-що.
Але так і не виходить поки (не розумію як), додати еластичності та відступів кнопкам у формі при зменшенні розмірів сторінки.

https://julia-shu.github.io/grid-template/

https://github.com/Julia-Shu

**Comment by Alecto** [comment]
6 - не исправлено

7)
скрипты не желательно в том месте, где вы их расположили
![image](https://user-images.githubusercontent.com/8464662/139381118-cb41fa63-efca-4c8a-bc86-aa12ac26edf3.png)

8)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/139381204-506adcc2-1a02-4081-87a4-9e69745d6d70.png)

9)
Отступы не соответствуют поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/139381263-2b6fd1a5-0319-4843-b4ba-929dec7d6db8.png)
![image](https://user-images.githubusercontent.com/8464662/139381306-79e65cc4-7661-49b9-a416-6af06533a1d4.png)

**Comment by Julia-Shu** [comment]
Добрий день, пане Андрію,
постаралася все виправити.

https://julia-shu.github.io/grid-template/

**Comment by Alecto** [comment]
10)
Отступы не соответствуют поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/139476717-a038e571-8ac2-4dc4-a187-9c870c2d30c9.png)

**Comment by Julia-Shu** [comment]
Вітаю, пане Андрію,
ось наступна правка
https://julia-shu.github.io/grid-template/

**Comment by Alecto** [comment]
11)
шрифт не соответствует для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/139629226-089cfefd-f0d9-463b-bdd3-71c417a49c09.png)


12)
отступы не соответсвуют для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/139629299-c529b5db-4834-40e0-a30d-ca74ad3d927e.png)

13)
отступы не соответсвуют для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/139629375-62cfbee8-8bb4-4af5-bca6-9bc84ea11f34.png)

**Comment by Julia-Shu** [comment]
Добрий вечір, пане Андрію,
виправляла, але не все ідеально виходить.
Зокрема, відступи у формі між кнопками на max-width: 575.8px
не такі, хоч намагалася.

https://julia-shu.github.io/grid-template/

**Comment by Alecto** [comment]
13 - не исправлено, констатирую как факт, также - форма создана неправильно, прошу переделать, убрав избыточные, лишние и необоснованные теги.

**Comment by Julia-Shu** [comment]
Добрий день, пане Андрію!
Нарешті знайшла, де ховалася помилка, дякую Вам за підказку :)

https://julia-shu.github.io/grid-template/
